<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class CarsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cars')->insert([
            [
                "brand_id" => 5,
                "title" => "Hyunday HB20",
                "sub_title" => "CONFORT 1.0 FLEX 5P MANUAL",
                "km" => "00.00",
                "fuel" => "GASOLINA",
                "exchange" => "AUTOMÁTICO",
                "doors" => "4",
                "air_conditioning" => 1,
                "airbag" => 1,
                "brake_abs" => 1,
                "information" => "LINK DO PDF",
                "end_plate" => "1",
                "color" => "vermelho magic",
                "deadline" => "2 dias úteis",
                "city" => "São Paulo",
                "store_withdrawn" => "SÃO PAULO",
                "plan" => "24 meses",
                "franchising" => "1.000 km",
                "price" => "899",
                "description" => "*Nos 3 primeiros meses e R$ 1.099,99 do 4 ao 24 mês",
                "image" => "HB20 Hatch.png"
            ],
            [
                "brand_id" => 2,
                "title" => "Crevolet Onyx",
                "sub_title" => "DRIVE 1.0 FLEX SP MANUAL",
                "km" => "00.00",
                "fuel" => "GASOLINA",
                "exchange" => "AUTOMÁTICO",
                "doors" => "4",
                "air_conditioning" => 1,
                "airbag" => 1,
                "brake_abs" => 1,
                "information" => "LINK DO PDF",
                "end_plate" => "1",
                "color" => "vermelho magic",
                "deadline" => "2 dias úteis",
                "city" => "São Paulo",
                "store_withdrawn" => "SÃO PAULO",
                "plan" => "24 meses",
                "franchising" => "1.000 km",
                "price" => "1.089",
                "description" => "*Nos 3 primeiros meses e R$ 1.299,99 do 4 ao 24 mês",
                "image" => "Onix Hatch.png"
            ],
            [
                "brand_id" => 5,
                "title" => "Hyunday HB20",
                "sub_title" => "1.6 16V FLEX 4P AUTOMATICO",
                "km" => "00.00",
                "fuel" => "GASOLINA",
                "exchange" => "AUTOMÁTICO",
                "doors" => "4",
                "air_conditioning" => 1,
                "airbag" => 1,
                "brake_abs" => 1,
                "information" => "LINK DO PDF",
                "end_plate" => "1",
                "color" => "vermelho magic",
                "deadline" => "2 dias úteis",
                "city" => "São Paulo",
                "store_withdrawn" => "SÃO PAULO",
                "plan" => "24 meses",
                "franchising" => "1.000 km",
                "price" =>  "1.289",
                "description" => "*Nos 3 primeiros meses e R$ 1.099,99 do 4 ao 24 mês",
                "image" => "Hb20s Evolution.png"
            ],
            [
                "brand_id" => 4,
                "title" => "Ford Ka",
                "sub_title" =>   "DRIVE 1.0 FLEX MANUAL",
                "km" => "00.00",
                "fuel" => "GASOLINA",
                "exchange" => "AUTOMÁTICO",
                "doors" => "4",
                "air_conditioning" => 1,
                "airbag" => 1,
                "brake_abs" => 1,
                "information" => "LINK DO PDF",
                "end_plate" => "1",
                "color" => "vermelho magic",
                "deadline" => "2 dias úteis",
                "city" => "São Paulo",
                "store_withdrawn" => "SÃO PAULO",
                "plan" => "24 meses",
                "franchising" => "Franquia 1.000 km",
                "price" => "1.389",
                "description" => "*Nos 3 primeiros meses e R$ 1.799,99 do 4 ao 24 mês",
                "image" => "ka.png"
            ],
            [
                "brand_id" => 4,
                "title" => "Ford Ecosport",
                "sub_title" => "2.0 4x2 FLEX 16V MANUAL",
                "km" => "00.00",
                "fuel" => "GASOLINA",
                "exchange" => "AUTOMÁTICO",
                "doors" => "4",
                "air_conditioning" => 1,
                "airbag" => 1,
                "brake_abs" => 1,
                "information" => "LINK DO PDF",
                "end_plate" => "1",
                "color" => "vermelho magic",
                "deadline" => "2 dias úteis",
                "city" => "São Paulo",
                "store_withdrawn" => "SÃO PAULO",
                "plan" =>    "24 meses",
                "franchising" => "Franquia 1.000 km",
                "price" => "1.599",
                "description" => "*Nos 3 primeiros meses e R$ 1.999,99 do 4 ao 24 mês",
                "image" => "Ecosport SE.png"
            ],
            [
                "brand_id" => 10,
                "title" => "Volkswagen Polo",
                "sub_title" =>   "ZEN 1.0 FLEX 12V 5P MANUAL",
                "km" => "00.00",
                "fuel" => "GASOLINA",
                "exchange" => "AUTOMÁTICO",
                "doors" => "4",
                "air_conditioning" => 1,
                "airbag" => 1,
                "brake_abs" => 1,
                "information" => "LINK DO PDF",
                "end_plate" => "1",
                "color" => "vermelho magic",
                "deadline" => "2 dias úteis",
                "city" => "São Paulo",
                "store_withdrawn" => "SÃO PAULO",
                "plan" =>    "24 meses",
                "franchising" => "Franquia 1.000 km",
                "price" => "1.899",
                "description" => "*Nos 3 primeiros meses e R$ 2.299,99 do 4 ao 24 mês",
                "image" => "polo.png"
            ],
            [
                "brand_id" => 3,
                "title" => "Fiat Strada",
                "sub_title" =>   "1.8 GLI 16V FLEX 4P AUTOMATICO",
                "km" => "00.00",
                "fuel" => "GASOLINA",
                "exchange" => "AUTOMÁTICO",
                "doors" => "4",
                "air_conditioning" => 1,
                "airbag" => 1,
                "brake_abs" => 1,
                "information" => "LINK DO PDF",
                "end_plate" => "1",
                "color" => "vermelho magic",
                "deadline" => "2 dias úteis",
                "city" => "Araruama",
                "store_withdrawn" => "RIO DE JANEIRO",
                "plan" =>    "24 meses",
                "franchising" => "Franquia 1.000 km",
                "price" => "2.500",
                "description" => "*Nos 3 primeiros meses e R$ 2.900,00 do 4 ao 24 mês",
                "image" => "strada.png"
            ],
            [
                "brand_id" => 3,
                "title" => "Fiat Toro",
                "sub_title" => "1.6 FLEX EXCLUSIVE TRONIC",
                "km" => "00.00",
                "fuel" => "GASOLINA",
                "exchange" => "AUTOMÁTICO",
                "doors" => "4",
                "air_conditioning" => 1,
                "airbag" => 1,
                "brake_abs" => 1,
                "information" => "LINK DO PDF",
                "end_plate" => "1",
                "color" => "vermelho magic",
                "deadline" => "2 dias úteis",
                "city" => "Belo Horizonte",
                "store_withdrawn" => "BH",
                "plan" => "24 meses",
                "franchising" => "Franquia 1.000 km",
                "price" => "2.799",
                "description" => "*Nos 3 primeiros meses e R$ 3.199,00 do 4 ao 24 mês",
                "image" => "toro.png"
            ],
            [
                "brand_id" => 8,
                "title" => "Nissan Kicks",
                "sub_title" => "1.8 16V FLEX 49 AUTOMATICO",
                "km" => "00.00",
                "fuel" => "GASOLINA",
                "exchange" => "AUTOMÁTICO",
                "doors" => "4",
                "air_conditioning" => 1,
                "airbag" => 1,
                "brake_abs" => 1,
                "information" => "LINK DO PDF",
                "end_plate" => "1",
                "color" => "vermelho magic",
                "deadline" => "2 dias úteis",
                "city" => "Rio de Janeiro",
                "store_withdrawn" => "SÃO PAULO",
                "plan" => "24 meses",
                "franchising" => "Franquia 1.000 km",
                "price" => "2.999",
                "description" => "*Nos 3 primeiros meses e R$ 3.599,99 do 4 ao 24 mês",
                "image" => "kicks.png"
            ]
        ]);
    }
}
